name: Auto approve
on:
  pull_request_target:
    branches:
      - "releases/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
